---

- hosts: all
  become: true
  tasks:

  - name: install apache2 packages to all Ubuntu Servers
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    
  - name: install apache and php for CentOS Servers
    apt:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
