---

- hosts: all
  become: true
  tasks:

    - name: install apache2 packages to all servers
      apt: 
        name: apache2
    
    - name: update repo index
      apt:
        update_cache: yes
        state: latest

    - name: add php support for apache2
      apt:
        name: libapache2-mod-php
        state: latest
